name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload files to PythonAnywhere
      run: |
        # Aqui você deve adicionar o comando para executar seu script de upload
        python3 upload-script.py
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        USERNAME: wictorlopes
        DOMAIN_NAME: wictorlopes.pythonanywhere.com

    - name: Reload webapp on PythonAnywhere
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        username: wictorlopes
        api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        domain-name: wictorlopes.pythonanywhere.com
